/*
 * This source file was generated by the Gradle 'init' task
 */
package com.VSS;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.transaction.annotation.EnableTransactionManagement;

@EnableTransactionManagement
@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try{
        System.out.println(new App().getGreeting());
        SpringApplication.run(App.class, args);}
        catch (Throwable t) {
            System.out.println(t.getMessage());
            t.printStackTrace();
        }

    }
}
