# Generated by Django 5.0.6 on 2024-10-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='images/photo.jpg', upload_to='profile_pictures/'),
        ),
    ]
